//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OblikControl.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringsTable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsTable() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OblikControl.Resources.StringsTable", typeof(StringsTable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка очистки суточного графика.
        /// </summary>
        public static string CleanDayGraphErr {
            get {
                return ResourceManager.GetString("CleanDayGraphErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистка суточного графика успешна.
        /// </summary>
        public static string CleanDGOK {
            get {
                return ResourceManager.GetString("CleanDGOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистка журнала событий успешна.
        /// </summary>
        public static string CleanELOK {
            get {
                return ResourceManager.GetString("CleanELOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка очистки журнала событий.
        /// </summary>
        public static string CleanEventsLogErr {
            get {
                return ResourceManager.GetString("CleanEventsLogErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЛО-3Tx-xMx.
        /// </summary>
        public static string CntrType1 {
            get {
                return ResourceManager.GetString("CntrType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЛО-3Tx-xPx.
        /// </summary>
        public static string CntrType2 {
            get {
                return ResourceManager.GetString("CntrType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тарификатор с RS-485.
        /// </summary>
        public static string CntrType3 {
            get {
                return ResourceManager.GetString("CntrType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тарификатор без RS-485.
        /// </summary>
        public static string CntrType4 {
            get {
                return ResourceManager.GetString("CntrType4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка контрольной суммы.
        /// </summary>
        public static string CSCError {
            get {
                return ResourceManager.GetString("CSCError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка данных.
        /// </summary>
        public static string DataError {
            get {
                return ResourceManager.GetString("DataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка получения параметров вычислений.
        /// </summary>
        public static string GetCalcUnitsErr {
            get {
                return ResourceManager.GetString("GetCalcUnitsErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка получения текущих значений.
        /// </summary>
        public static string GetCurrentValuesErr {
            get {
                return ResourceManager.GetString("GetCurrentValuesErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текушие значения получены успешно.
        /// </summary>
        public static string GetCVOK {
            get {
                return ResourceManager.GetString("GetCVOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка получения суточного графика.
        /// </summary>
        public static string GetDayGraphListErr {
            get {
                return ResourceManager.GetString("GetDayGraphListErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Суточный график получен успешно.
        /// </summary>
        public static string GetDayGraphListOK {
            get {
                return ResourceManager.GetString("GetDayGraphListOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка получения количества записей суточного графика.
        /// </summary>
        public static string GetDayGraphRecsErr {
            get {
                return ResourceManager.GetString("GetDayGraphRecsErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные о размере суточного графика получены.
        /// </summary>
        public static string GetDGROK {
            get {
                return ResourceManager.GetString("GetDGROK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Версия ПО получена успешно.
        /// </summary>
        public static string GetFWVerOK {
            get {
                return ResourceManager.GetString("GetFWVerOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка получения версии прошивки.
        /// </summary>
        public static string GetFWVersionErr {
            get {
                return ResourceManager.GetString("GetFWVersionErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки сети получены успешно.
        /// </summary>
        public static string GetNetOk {
            get {
                return ResourceManager.GetString("GetNetOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка получения настроек сети.
        /// </summary>
        public static string GetNetworkConfigErr {
            get {
                return ResourceManager.GetString("GetNetworkConfigErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Карта сегментов получена успешно.
        /// </summary>
        public static string GetSegMapOK {
            get {
                return ResourceManager.GetString("GetSegMapOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка получения карты сегментов.
        /// </summary>
        public static string GetSegmentsMapErr {
            get {
                return ResourceManager.GetString("GetSegmentsMapErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка получения показаний времени счетчика.
        /// </summary>
        public static string GetTimeErr {
            get {
                return ResourceManager.GetString("GetTimeErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время счетчика получено успешно.
        /// </summary>
        public static string GetTimeOK {
            get {
                return ResourceManager.GetString("GetTimeOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка контрольной суммы.
        /// </summary>
        public static string L1CSCError {
            get {
                return ResourceManager.GetString("L1CSCError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Успешное выполнение запроса.
        /// </summary>
        public static string L1OK {
            get {
                return ResourceManager.GetString("L1OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переполнение входного буфера счетчика.
        /// </summary>
        public static string L1Overflow {
            get {
                return ResourceManager.GetString("L1Overflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неизвестная ошибка L1.
        /// </summary>
        public static string L1Unk {
            get {
                return ResourceManager.GetString("L1Unk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Успешное выполнение операции.
        /// </summary>
        public static string L2Err00 {
            get {
                return ResourceManager.GetString("L2Err00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрещена смена пароля.
        /// </summary>
        public static string L2ErrF5 {
            get {
                return ResourceManager.GetString("L2ErrF5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неправильно задана команда стирания графиков.
        /// </summary>
        public static string L2ErrF6 {
            get {
                return ResourceManager.GetString("L2ErrF6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неправильный пароль.
        /// </summary>
        public static string L2ErrF7 {
            get {
                return ResourceManager.GetString("L2ErrF7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Длина данных задана равной 0.
        /// </summary>
        public static string L2ErrF8 {
            get {
                return ResourceManager.GetString("L2ErrF8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неправильный запрос на запись (несоответствие запрашиваемой и действительной длины данных).
        /// </summary>
        public static string L2ErrF9 {
            get {
                return ResourceManager.GetString("L2ErrF9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неправильно задано смещение.
        /// </summary>
        public static string L2ErrFA {
            get {
                return ResourceManager.GetString("L2ErrFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет права доступа к данным.
        /// </summary>
        public static string L2ErrFB {
            get {
                return ResourceManager.GetString("L2ErrFB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неправильно задан уровень пользователя.
        /// </summary>
        public static string L2ErrFC {
            get {
                return ResourceManager.GetString("L2ErrFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректная операция (Попытка записи в сегмент чтения и наоборот).
        /// </summary>
        public static string L2ErrFD {
            get {
                return ResourceManager.GetString("L2ErrFD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неправильный идентификатор сегмента.
        /// </summary>
        public static string L2ErrFE {
            get {
                return ResourceManager.GetString("L2ErrFE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректный запрос (содержит менее 5 байт).
        /// </summary>
        public static string L2ErrFF {
            get {
                return ResourceManager.GetString("L2ErrFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неизвестная ошибка L2.
        /// </summary>
        public static string L2ErrUnk {
            get {
                return ResourceManager.GetString("L2ErrUnk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль успешно установлен.
        /// </summary>
        public static string PwdSetOK {
            get {
                return ResourceManager.GetString("PwdSetOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрещена смена пароля системному пользователю.
        /// </summary>
        public static string PwdSetUserErr {
            get {
                return ResourceManager.GetString("PwdSetUserErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка выполнения запроса.
        /// </summary>
        public static string QueryErr {
            get {
                return ResourceManager.GetString("QueryErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные выходят за допустимый диапазон.
        /// </summary>
        public static string RangeErr {
            get {
                return ResourceManager.GetString("RangeErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка чтения.
        /// </summary>
        public static string ReadError {
            get {
                return ResourceManager.GetString("ReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка обработки запроса.
        /// </summary>
        public static string ReqError {
            get {
                return ResourceManager.GetString("ReqError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка чтения сегмента.
        /// </summary>
        public static string SegReadErr {
            get {
                return ResourceManager.GetString("SegReadErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка записи в сегмент.
        /// </summary>
        public static string SegWriteErr {
            get {
                return ResourceManager.GetString("SegWriteErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправка запроса....
        /// </summary>
        public static string SendReq {
            get {
                return ResourceManager.GetString("SendReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка установки параметров вычислений.
        /// </summary>
        public static string SetCalcUnitsErr {
            get {
                return ResourceManager.GetString("SetCalcUnitsErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка установки времени.
        /// </summary>
        public static string SetCurrentTimeErr {
            get {
                return ResourceManager.GetString("SetCurrentTimeErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текущее время установлено.
        /// </summary>
        public static string SetCurrTimeOK {
            get {
                return ResourceManager.GetString("SetCurrTimeOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки сети установлены успешно.
        /// </summary>
        public static string SetNetOK {
            get {
                return ResourceManager.GetString("SetNetOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка установки настроек сети.
        /// </summary>
        public static string SetNetworkConfigErr {
            get {
                return ResourceManager.GetString("SetNetworkConfigErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка установки пароля пользователю.
        /// </summary>
        public static string SetPasswordErr {
            get {
                return ResourceManager.GetString("SetPasswordErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Таймаут.
        /// </summary>
        public static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Администратор.
        /// </summary>
        public static string UsrAdmin {
            get {
                return ResourceManager.GetString("UsrAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Энергонадзор.
        /// </summary>
        public static string UsrEnrego {
            get {
                return ResourceManager.GetString("UsrEnrego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Системный пользователь.
        /// </summary>
        public static string UsrSystem {
            get {
                return ResourceManager.GetString("UsrSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неизвестный пользователь.
        /// </summary>
        public static string UsrUnk {
            get {
                return ResourceManager.GetString("UsrUnk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь.
        /// </summary>
        public static string UsrUsr {
            get {
                return ResourceManager.GetString("UsrUsr", resourceCulture);
            }
        }
    }
}
